### PR TITLE
RHMAP-10954 Updating nagios-api code

### PR DESCRIPTION
**Pull request by kpiwko**
Update nagios-api to get more functionality

### CODE REVIEW

**Comment by kpiwko** [comment]
@ciaran-byrne @jasonmadigan you probably might want to have a look

**Comment by ciaran-byrne** [comment]
I've no massive objection to this, but would appreciate a look from @philbrookes

**Comment by philbrookes** [comment]
It seems fine, I'd recommend making sure fh-toolkit is still functioning with this update though. It may require some updates to that tool, if any responses that fh-toolkit uses have been modified; but looking over these changes, I don't think any of them have been.

**Comment by kpiwko** [comment]
Closing this request as obsolete.

**Pull request closed without merging**
